### ISSUE TITLE
ValueError: could not convert string to float: s

### ISSUE THREAD

**Issue by brianrusso** [ContinuumIO/topik#76]
I get this identical error on both Ubuntu 15 + pip install (or directly from the latest github) AND on Ubuntu 14 LTS + conda2; so I am pretty sure this is not an issue with my environment.

Following the tutorial on the movie reviews data (not sure if that matters).. I get..

brian@niihau:[~]$ topik -d reviews -c text
2016-04-18 14:29:00,880 : WARNING : too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy
Traceback (most recent call last):
  File "/home/brian/anaconda2/bin/topik", line 6, in <module>
    sys.exit(run())
  File "/home/brian/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/simple_run/cli.py", line 27, in run
    termite_plot=termite)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/simple_run/run.py", line 67, in run_pipeline
    model = models.registered_models[model](vectorized_data, ntopics=ntopics, **kwargs)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/models/lda.py", line 82, in lda
    return ModelOutput(vectorized_corpus=vectorized_output, model_func=_LDA, ntopics=ntopics, **kwargs)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/models/base_model_output.py", line 20, in __init__
    vectorized_corpus, **kwargs)
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/models/lda.py", line 72, in _LDA
    for topic_no in range(ntopics)}
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/models/lda.py", line 72, in <dictcomp>
    for topic_no in range(ntopics)}
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/models/lda.py", line 12, in _topic_term_to_array
    term_scores = {term: float(score) for score, term in topic}
  File "/home/brian/anaconda2/lib/python2.7/site-packages/topik/models/lda.py", line 12, in <dictcomp>
    term_scores = {term: float(score) for score, term in topic}
ValueError: could not convert string to float: s

**Comment by brianrusso** [comment]
Looks like PLSA model works ok; though i had to hack the ldavis code a bit to get it to output since I run everything in VMs via ssh (i.e. it binding the web server to 'localhost' does me no good). Hardcoding works okay though this is kinda a hack. Will try to fix it properly and submit if I get the chance.

**Comment by herrtao** [comment]
I confront the same problem, I always received the same error when I try the movie reviews data. Can you tell me how you fix the issue?
